inspirehep/inspire-crawler

- INSTALL.rst
- README.rst
- docs/api.rst
- docs/conf.py
- docs/index.rst
- docs/usage.rst
- inspire_crawler/config.py
- inspire_crawler/errors.py
- inspire_crawler/models.py
Signed-off-by: Jan Aage Lavik <jan.age.lavik@cern.ch>
> docs: major update

- inspire_crawler/config.py
- inspire_crawler/errors.py
- inspire_crawler/models.py
- inspire_crawler/receivers.py
- inspire_crawler/tasks.py
- inspire_crawler/utils.py
- tests/test_tasks.py
- tests/test_utils.py
* models: improved saving and handling
* utils: make sure OAI XML generated is parsable XML
> Improvements after QA

- CHANGES.rst
- RELEASE-NOTES.rst
- inspire_crawler/version.py
Signed-off-by: Eamonn Maguire <eamonnmag@gmail.com>
> setup: release v0.2.2

- inspire_crawler/tasks.py
> logs: Added some extra logs to submit_records

- setup.py
* We were pinning it to the middle number.
> packaging: fix autosemver pin to major

- setup.py
> Pin invenio-workflows to major version

- .travis.yml
Also bump the version, as there's some unsynch with pypi
Sem-Ver: feature
> travis: remove unused mysql config

- inspire_crawler/cli.py
- inspire_crawler/ext.py
- run-tests.sh
> cli: add minimal cli helper commands

- inspire_crawler/receivers.py
- inspire_crawler/utils.py
- tests/test_utils.py
Signed-off-by: Samuele Kaplun <samuele.kaplun@cern.ch>
> utils: use upstream oaiharvester/write_to_dir

- .travis.yml
- inspire_crawler/cli.py
- inspire_crawler/models.py
- inspire_crawler/tasks.py
- inspire_crawler/utils.py
> cli: add schedule command

- .gitignore
- inspire_crawler/alembic/34b150f80576_create_inspire_crawler_tables.py
- inspire_crawler/alembic/df8d1c51b820_create_inspire_crawler_branch.py
- setup.py
- tests/alembic/test_alembic.py
Signed-off-by: Zacharias Zacharodimos <zacharias.zacharodimos@cern.ch>
> bump `invenio-workflows` to version 7.0

- inspire_crawler/tasks.py
> submit_results: store source data too

- inspire_crawler/tasks.py
> tasks: use correct config value for queue

- inspire_crawler/tasks.py
> tasks.schedule_crawl: return a serializable

- inspire_crawler/cli.py
- setup.py
- tests/test_cli.py
- tests/test_tasks.py
Straightforward, but still needs tests.
> cli: fix schedule command

- inspire_crawler/tasks.py
Signed-off-by: Antonio Cesarano <cesarano2607@gmail.com>
> tasks: fix workflow start if there aren't errors

- inspire_crawler/tasks.py
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> tasks: add engine to the workflow

- .travis.yml
Signed-off-by: Harris Tzovanakis <me@drjova.com>
> travis: remove sqlite

- docs/api.rst
- setup.py
~~This fails locally~~, let's see what Travis says...
> setup: bump celery to version ~4.0

- inspire_crawler/cli.py
- tests/test_cli.py
> cli: fix bad id shown in the schedule message

- inspire_crawler/alembic/df8d1c51b820_create_inspire_crawler_branch.py
> alembic: add branch label
